### PR TITLE
Object copying and secondary constructors

### PR DESCRIPTION
**Pull request by g4s8**
* Corrected constructors arguments parsing
 * Implemented object copying
 * Generate java code for secondary constructors

### CODE REVIEW

**Comment by pa9ey** [comment]
Hey, I'm interested here. What license are we using? The MIT License?
Yes, the MIT License.
What about in this file?
Oh, the MIT License.
And this file?
The MIT License
And how about in this file?
The MIT License.
And this?
The MIT License
And in this?
The MIT License.
Ah yes, but this file. What are we using here?
The MIT License.
And here?
The MIT License.
Is there any code in this file?
Yes there is, if you scroll down a bit. (Hint: It's after the license.)
Is the code important?
No, not really. The main thing is that we know what license we're using.
Oh right. What license are we using in this file? The MIT License?
Yep. The MIT License.
And in this one...?

Nothing personal @g4s8. I know these are the "rules". :)

Right.
Now that I've offended everybody, I'm going to bed.
Sorry.

(Well, only a little bit.)

**Comment by yegor256** [comment]
@g4s8 the code looks really good, I'm glad to see it here, thanks! I'm ready to merge if there no objections from anyone

**Comment by pa9ey** [comment]
@yegor256 I have a bunch of objections but the ones I've tried so far aren't going over very well. My assumption at the moment is that the best thing to do is just get lots of code in. As long as Qulice doesn't complain then that's the main thing, as far as quality is concerned. We don't need to worry about naming and readability or usefulness of comments or completeness of tests. Or bugs even. Just get lots of code going in. We can worry about that other stuff later. Maybe.

I genuinely don't mean to be snarky there. I just think I'm recognising a difference in approach which I'm slowly getting used to. I'm going to work on my check-in today/tomorrow and try and get that code in. I don't think it will perceived as that useful or as moving the thing on very much but it will highlight some bugs and deficiencies in the tests so far at least.

My failing perhaps is that I want to understand everything that's going in. And it's likely that it's just that I'm not up to speed on a lot of these things so I perhaps have difficulties where other more knowledgeable people don't at all, and I'm over-compensating for that with my objections and my desire to have everything "just so".

Just speaking my mind here. I'm willing to change and learn if necessary. As I've said, I'm certainly going to try and crack on with this anyway, and see if I can catch up somewhat.

Be more brutal with me if necessary. :)

**Comment by g4s8** [comment]
@yegor256 anytime!

@pa9ey as I understand, our main goal now is to get working compiler prototype. Some minor bugs are acceptable just as in any prototype. The main thing is to be able to compile eo-code into executable program and try EO in use.

**Comment by pa9ey** [comment]
> The main thing is to be able to compile eo-code into executable program and try EO in use.

I do agree with that @g4s8 (even though talk of prototypes make me nervous), which is why I'll no doubt have to lighten up a bit. I'm just having to re-calibrate my thinking a little.

Although, I'm not sure I'll ever make my peace with names like `ArgCpObject`. :p

**Comment by pa9ey** [comment]
@g4s8 and @yegor256 let's get this in then! :) Let's get our first real program happening asap.

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by g4s8** [comment]
@yegor256 I've fixed PDD syntax error, could you please restart rultor?

**Comment by pa9ey** [comment]
@rultor Can you merge this for @g4s8 please? ;)

**Comment by yegor256** [comment]
@rultor try to merge

**Pull request merged**
