### PR TITLE
#43: Changed Book representation from String to Text

### PR DESCRIPTION
**Pull request by Tradunsky**

### CODE REVIEW

**Comment by pa9ey** [comment]
@Tradunsky Was the idea to get rid of (rename) the `String` type altogether?

**Comment by yegor256** [comment]
@Tradunsky yes, I second @pa9ey here. I thought that you wanted to replace `String` by `Text` everywhere

**Comment by Tradunsky** [comment]
@yegor256, the name of the issue #43 is self-described. 
And I had no intention to get rid of String everywhere, because a type Text won't fit as a name of a Person, title or isbn of a Book.

And there are cases, when String cannot and shouldn't be replaced with Text, for example:

> object ("John") as Person:
>     String @name //should we use a type Name instead?
and
> cli:
>   printed:
>     string:
>       **"Hello, world!"**
and 
> object zero(0, "USD") as Money:
>  Int @amount
>  String @currency
and so on.

if we replaced String with Text everywhere how would string literal changed?
Where quotes like "" would be treated just like Text and where other types like Word or Sentence, Identity, Currency?

I don't suggest we to dive into a long discussion about what String is should like, I just suggest we change human-readable representation according to [Text_(literary_theory)](https://en.wikipedia.org/wiki/Text_(literary_theory))

**Comment by pa9ey** [comment]
@Tradunsky Okay. I guess I'm not following what you're trying to do then really. I'll go back to the chatting on the Issue.

**Comment by yegor256** [comment]
@Tradunsky I closed this one, since we just merged #67

**Pull request closed without merging**
