### PR TITLE
Add initial `.gitignore` file

### PR DESCRIPTION
**Pull request by alexpanov**

### CODE REVIEW

**Comment by pchmielowski** [comment]
Why .idea and .DS_Store?

**Comment by alexpanov** [comment]
Because I work on a Mac and use Intellij IDEs. As far as I know, it's a very popular setup.
Do you think something else should go there?

**Comment by pchmielowski** [comment]
I'm not sure if there is any reason for including now the file with initial configuration for one of the IDE's which may be used in the future but no one is sure...

**Comment by alexpanov** [comment]
Well then it boils down to 2 basic questions:

- Is it worth having `.gitignore`?
- If yes, then does it make sense to have it empty?

If the answer to the second question is `no`, then I wonder what would you prefer to have there instead.

**Comment by pchmielowski** [comment]
I'm a fan of the [YAGNI principle](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it) both in code and in life :) So IMO, there is no need to add anything what is not necessary now.

**Comment by alexpanov** [comment]
I had to manually exclude my `.idea` folder just as it would be the case for any repository that does not have a `.gitignore`.
I don't see any difference between this repository and, say, https://github.com/yegor256/tacit.

Are you saying that `.gitignore` is not needed provided it ignores only `.idea`? Should I add something else?

**Comment by phase** [comment]
If you're going to make a PR for a Java setup, you should at least include other people's setups. What if I'm on Windows running Eclipse? Or Linux running Netbeans? You should at least have [something like this](https://www.gitignore.io/api/java%2Ceclipse%2Cnetbeans%2Cintellij%2Cmacos), but I'd venture to say that one isn't needed in the project's current state. Until an initial code implementation and license are setup, ignore IntelliJ files shouldn't be worried about. These three are usually put together in the same commit.

**Comment by yegor256** [comment]
I agree with the YAGNI principle mentioned here, but IntelliJ is just the best IDE on the market :) So, it deserves to be in our `.gitignore`

**Comment by yegor256** [comment]
@alexpanov thanks!

**Comment by alexpanov** [comment]
@phase I haven't mentioned Java. Intellij has many IDEs for different languages and platforms.
As a matter of fact, I was using PyCharm to submit this PR.

**Pull request merged**
