### PR TITLE
Laconic syntax

### PR DESCRIPTION
**Pull request by gukoff**
In continuation of https://github.com/yegor256/eo/issues/12

Also, I've replaced 2-whitespace indentation to 4 and took a new constructor syntax. Perhaps, the new(not well thought out) constructor syntax doesn't belong to the pull request.

### CODE REVIEW

**Comment by mdbs99** [comment]
That's I'm talking about. I like, always, to use only 2 whitespace to indent. You propose 4 as a rule of the compiler?
What is the `@` in constructor? I think we will use `@` for attributes, see #10.

**Comment by gukoff** [comment]
Not at all; the indentation level is up to you. The only requirement is for the same indentation level of the code within a block.
Speaking of the `@` operator, I've written a brief explanation in the linked issue. The only reason for it, is a belief that a constructor may contain some preparation commands apart from the attribute initialisation. Otherwise, one could come up with a more suitable syntax.

**Comment by pa9ey** [comment]
As far as this particular diff goes, I prefer the new version. I like the terseness.
I reserve the right to change my mind as the whole thing develops though. :)

**Comment by gukoff** [comment]
So am I :) It's all about looking for new ideas!

**Comment by yegor256** [comment]
@gukoff thanks!

**Pull request merged**
