### PR TITLE
eo-core lib

### PR DESCRIPTION
**Pull request by g4s8**
First EO library:
EO types defenition in `types.eo` and java implementations of `not`, `equals`, `sum`, `diff`.

To build:
```bash
cd eo-core
mvn clean compile
```

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by yegor256** [comment]
@rultor merge

**Comment by g4s8** [comment]
@yegor256 fixed there

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
