### PR TITLE
Object xml schema

### PR DESCRIPTION
**Pull request by g4s8**
#147 - eo object xml schema

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/eo#149` is in scope.

**Comment by yegor256** [comment]
@g4s8 I doubt it will build, since XML formatting is totally off and XCOP is there) Let's try

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@g4s8 there are some issues with XML, please run:

```
xcop --fix --license LICENSE.txt $(find . -name '*.xml' -o -name '*.xsl')
```

**Comment by g4s8** [comment]
@yegor256 fixed, please try again

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/eo#149`.

**Comment by 0crat** [comment]
Job `gh:yegor256/eo#149` is now out of scope.

**Pull request merged**
