### PR TITLE
Adding a StreamOutput so that compiled eo examples can be output to the console.

### PR DESCRIPTION
**Pull request by pa9ey**
This was useful for me as I was working out what the compiler does exactly. It also shows some deficiencies in the current compiler.
The command line argument "--demo" can now be used to show the various eo example files and their compiled output.
I had to duplicate the resource eo files, which is a shame, but I don't yet know how to avoid that.

### CODE REVIEW

**Comment by pa9ey** [comment]
I'd made these changes anyway for my own benefit and learning. If they're not useful more generally then that's fine. Maybe they'll just be useful for a while until we improve the tests?

**Comment by pa9ey** [comment]
Here's what the output looks like in IntelliJ:

```
=====================
EOLANG:
type Book:
    Text text()

JAVA:
public interface Book {
    Text text();
}
=====================


=====================
EOLANG:
type Car:
    Money cost()
    Bytes picture()
    Car moveTo(Coordinates coords)
JAVA:
public interface Car {
    Money cost();
    Bytes picture();
    Car moveTo(final Coordinates coords);
}
=====================


=====================
EOLANG:
object fibonacci as Int:
  Int @n
  ctor():
    fibonacci:
      1
  Int int():
    if:
      firstIsLess:
        @n
        2
      1
      plus:
        @n
        fibonacci:
          minus:
            @n
            1
JAVA:
line 6:2 extraneous input ' ' expecting DEDENT
line 5:2 missing NEWLINE at ' '
line 6:2 extraneous input 'Int' expecting {<EOF>, 'type', 'object', LONAME}
line 6:9 extraneous input '(' expecting {<EOF>, 'type', 'object', LONAME}
line 10:8 extraneous input ' ' expecting {<EOF>, 'type', 'object', LONAME}
line 14:8 extraneous input ' ' expecting {<EOF>, 'type', 'object', LONAME}
line 17:12 extraneous input ' ' expecting {<EOF>, 'type', 'object', LONAME}
public final class fibonacci implements Int {
 private final Int n;

public fibonacci(final Int n) {
 this.n = n; 
}
}
=====================


=====================
EOLANG:
type Number:
    Integral integral()
    Decimal decimal()

type Text:
    Number length()
    Collection lines()
JAVA:
public interface Text {
    Number length();
    Collection lines();
}public interface Number {
    Integral integral();
    Decimal decimal();
}
=====================


=====================
EOLANG:
type Pixel:
  Pixel moveTo(Integer x, Integer y)

JAVA:
public interface Pixel {
    Pixel moveTo(final Integer x, final Integer y);
}
=====================


=====================
EOLANG:
object zero as Money, Int:
    Int @amount
    Text @currency
    ctor(Int amount, Text currency)

JAVA:
public final class zero implements Money, Int {
 private final Int amount;
private final Text currency;

public zero(final Int amount, final Text currency) {
 this.amount = amount;
this.currency = currency; 
}
}
=====================
```

**Comment by yegor256** [comment]
@pa9ey good idea, but the problem with file duplication is so obvious that we have to fix it. I believe, we have to do it all a bit differently. I should be able to do:

```
$ java -jar eolang.jar --demo
```

This should output _all_ `.eo` files available in `src/main/resources/eo`. For example:

```
$ java -jar eolang.jar --demo
test.eo
car.eo
simple/fibonacci.eo
```

Then, I should be able to do:

```
$ java -jar eolang.jar --demo simple/fibonacci.eo
```

And get what you're printing now.

And, we have to use the same files in our tests. Just remove them from `src/test/resources` and point tests to `src/main/resource` (should happen automatically, if you don't change their names and paths).

**Comment by pa9ey** [comment]
@yegor256 Agreed. You know how much I dislike pointless duplication. ;)
I'll have a crack at sorting it all out.

**Comment by pa9ey** [comment]
@yegor256 A request from a Java/Open Source noob who is a bit unsure of himself...

1. I have an almost ready fix for this that is very if-else-y, ugly, and horribly procedural, and has some code stolen straight from a stackoverflow answer, but it would at least work. I could submit this soon. (I could even add a puzzle for making it more OO.)

2. I could tidy up the whole thing and make it more OO but this pull request might have to sit around for a while.

3. I could do 2. but submit the fix from 1. first for comment (I'm learning here and would welcome advice), and then the whole fix could be pulled when I've made it more OO.

I don't particularly mind either way, but which would you prefer? :)

**Comment by pa9ey** [comment]
@yegor256 Oh boy. What a fool I am. I should have known that Qulice wasn't going to let me get away with the ugly procedural version... 😆

The static analysis is absolutely brutal. I might have some quibbles with it, and there might be some things I don't understand yet... but I'm impressed.

**Comment by pchmielowski** [comment]
@pa9ey - I don't understand - As far I see, all checks have passed = Qulice "approved" your code. Am I right?

BTW It is not the prettiest code and has one big problem - mixing levels of abstraction: in one method you are low-level programmer who manipulate with `stdout` and then, you are high level programmer who just create objects and delegate the tasks to them.
**Anyway**, your code is better than 95% of code in the world - it needs refactoring but it is easy to refactor.

**Comment by pa9ey** [comment]
@pchmielowski I'm referring to the stuff I'm working on right now. I've been trying to fix it according to this comment: https://github.com/yegor256/eo/pull/116#issuecomment-275997419. But I've been trying to achieve No.1 in my list of options above. I just found it interesting that I couldn't actually achieve that because Qulice won't let me. It's looks like it's going to force me to be more OO. That's kinda cool. I'm an advocate of static analysis in theory (although circumstances at work haven't let me try it in practice), I just didn't realise it could be so brutal - and perhaps so effective. :)

**Comment by pa9ey** [comment]
@yegor256 and @pchmielowski: I'm gonna go for option 2 then... But like I said, this PR might have to sit here a while... All good though. I'm learning stuff.

**Comment by pa9ey** [comment]
Closing this PR, and will resubmit when I've done a proper solution.

**Pull request closed without merging**
