### PR TITLE
#83: decorators

### PR DESCRIPTION
**Pull request by yegor256**
As suggested in #83: decorators introduced

### CODE REVIEW

**Comment by yegor256** [comment]
I'm ready to merge. Any complaints/ideas?

**Comment by g4s8** [comment]
What about decorator's constructor? I think we should require decorating object as primary constructor parameter (in hidden primary constructor) and allow to make secondary constructors:
```
object one decorates zero:
  ctor() # secondary ctor
    one 1
  ctor(num) # secondary ctor
    zero num # call primary ctor
  Text print:
    origin.asText() # here
```
@yegor256 what do you think?

**Comment by yegor256** [comment]
@g4s8 you're right, added here: c0ed2e3

**Comment by ixmanuel** [comment]
Decoration is an empty name for this purpose. It is not an appropriate concept for what we really do when we use this pattern. 

- Decorate: make (something) look more attractive by adding extra items or images to it.
- Decoration: the process or art of decorating or adorning something.
- Decorator: a person who decorates, in particular:  a person whose job is to design the interior of someone's home, by choosing colours, ...

What we do is an extension:
- Extension: an application of an existing system or activity to a new area: direct marketing is an extension of telephone selling.
See its applications in the Thesaurus: 
1 they are planning a new extension: addition, adjunct, annex, wing, supplementary building, ell, add-on, bump-out.
2 an extension of knowledge: expansion, increase, enlargement, widening, broadening, deepening; augmentation, enhancement, development, growth, continuation.

Decorate. (n.d). In OxfordDictionaries.com. Retrieved from https://en.oxforddictionaries.com/definition/decorate
Decoration. (n.d). In OxfordDictionaries.com. Retrieved from https://en.oxforddictionaries.com/definition/decoration
Decorator. (n.d). In OxfordDictionaries.com. Retrieved from https://en.oxforddictionaries.com/definition/decorator
Extension. (n.d). In OxfordDictionaries.com. Retrieved from https://en.oxforddictionaries.com/definition/extension

**Pull request merged**
