### PR TITLE
for, while, if aren't operators

### PR DESCRIPTION
**Pull request by fabriciofx**
for, while, if, etc aren't operators. They are keywords which changes program's execution flow.

### CODE REVIEW

**Comment by pa9ey** [comment]
Aren't they objects rather than keywords?

**Comment by fabriciofx** [comment]
@pa9ey In EO they're objects, but in other languages (like Java) they're keywords.

**Comment by pa9ey** [comment]
Agreed. But doesn't that (partly) invalidate your change?

**Comment by fabriciofx** [comment]
@pa9ey I'm sorry, but I don't understand why invalidate my change. Observes the change is in the "dont tolerate" section.

**Comment by yegor256** [comment]
@fabriciofx I would say "control flow statements": https://en.wikipedia.org/wiki/For_loop

**Comment by pa9ey** [comment]
@fabriciofx Whoops. My apologies! You're right.

**Comment by fabriciofx** [comment]
@yegor256 I agree. Changed. Could you verify if is it correct now?

**Comment by yegor256** [comment]
@fabriciofx yes, thanks!

**Pull request merged**
