### PR TITLE
Fix #93 - Remove Joiner dependency

### LINKED ISSUE #93: Remove Joiner dependency
Let's remove the `Joiner` dependency, because we can use JDK's `String.join()` to do same thing.

### PR DESCRIPTION
**Pull request by fabriciofx**

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@fabriciofx there seems to be some quality problems with your code (see above)

**Comment by yegor256** [comment]
@fabriciofx what's up with this PR? Planning to finish?

**Comment by fabriciofx** [comment]
@yegor256 I'm sorry. I was on vacations. I would like correct it.

**Comment by pa9ey** [comment]
@fabriciofx I had the same problem. I didn't spot the README actually has the answer already. :) https://github.com/yegor256/eo#how-to-contribute

**Comment by fabriciofx** [comment]
@pa9ey Yeah, the "how to contribute" page it would be nice! :)

**Comment by fabriciofx** [comment]
@pa9ey I figured it now. Thanks! :)

**Pull request closed without merging**
