### PR TITLE
#17: fibonacci example

### PR DESCRIPTION
**Pull request by yegor256**
As discussed in #17 here is my Fibonacci example

### CODE REVIEW

**Comment by gukoff** [comment]
Looks unusual. The thing I don't really like is the fact that the type/object declaration, an inside of a method and a constructor call are all looking the same, although they are absolutely different things(yet). Usually, different types of brackets are used to distinguish between different usage cases.

I feel a bit of incompleteness. What if a method contains more than one instruction? How would a method call look? A method call without arguments?

**Comment by yegor256** [comment]
@gukoff I will surprise you, but all methods will have only one "instruction" :)

**Comment by gukoff** [comment]
> @gukoff I will surprise you, but all methods will have only one "instruction" :)

Yep, that's what the first question is hinting about :) Shouldn't it become a requirement? I like to write one-line methods, but am not sure if it should be a restriction.
What about the other questions?

**Comment by yegor256** [comment]
@gukoff as for the "anonymous objects" -- let's create a separate ticket.

**Comment by yegor256** [comment]
@gukoff I'll merge this thing and please submit new tickets with your concerns, we'll go through them one by one

**Pull request merged**
